//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExplorerTabUtility.Resources {
    using System;
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExplorerTabUtility.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string About_BeFirstSupporter {
            get {
                return ResourceManager.GetString("About_BeFirstSupporter", resourceCulture);
            }
        }
        
        public static string About_BuyMeACoffee {
            get {
                return ResourceManager.GetString("About_BuyMeACoffee", resourceCulture);
            }
        }
        
        public static string About_CurrentSupporters {
            get {
                return ResourceManager.GetString("About_CurrentSupporters", resourceCulture);
            }
        }
        
        public static string About_Description {
            get {
                return ResourceManager.GetString("About_Description", resourceCulture);
            }
        }
        
        public static string About_Developer {
            get {
                return ResourceManager.GetString("About_Developer", resourceCulture);
            }
        }
        
        public static string About_GitHubSponsors {
            get {
                return ResourceManager.GetString("About_GitHubSponsors", resourceCulture);
            }
        }
        
        public static string About_Patreon {
            get {
                return ResourceManager.GetString("About_Patreon", resourceCulture);
            }
        }
        
        public static string About_PayPal {
            get {
                return ResourceManager.GetString("About_PayPal", resourceCulture);
            }
        }
        
        public static string About_StarOnGitHub {
            get {
                return ResourceManager.GetString("About_StarOnGitHub", resourceCulture);
            }
        }
        
        public static string About_SupportDescription {
            get {
                return ResourceManager.GetString("About_SupportDescription", resourceCulture);
            }
        }
        
        public static string About_SupportHelps {
            get {
                return ResourceManager.GetString("About_SupportHelps", resourceCulture);
            }
        }
        
        public static string About_SupportProject {
            get {
                return ResourceManager.GetString("About_SupportProject", resourceCulture);
            }
        }
        
        public static string About_SupportersDescription {
            get {
                return ResourceManager.GetString("About_SupportersDescription", resourceCulture);
            }
        }
        
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        public static string DefaultProfile_Duplicate {
            get {
                return ResourceManager.GetString("DefaultProfile_Duplicate", resourceCulture);
            }
        }
        
        public static string DefaultProfile_Home {
            get {
                return ResourceManager.GetString("DefaultProfile_Home", resourceCulture);
            }
        }
        
        public static string DefaultProfile_ReopenClosed {
            get {
                return ResourceManager.GetString("DefaultProfile_ReopenClosed", resourceCulture);
            }
        }
        
        public static string Enum_HotkeyScope_FileExplorer {
            get {
                return ResourceManager.GetString("Enum_HotkeyScope_FileExplorer", resourceCulture);
            }
        }
        
        public static string Enum_HotkeyScope_Global {
            get {
                return ResourceManager.GetString("Enum_HotkeyScope_Global", resourceCulture);
            }
        }
        
        public static string Enum_HotKeyAction_DetachTab {
            get {
                return ResourceManager.GetString("Enum_HotKeyAction_DetachTab", resourceCulture);
            }
        }
        
        public static string Enum_HotKeyAction_Duplicate {
            get {
                return ResourceManager.GetString("Enum_HotKeyAction_Duplicate", resourceCulture);
            }
        }
        
        public static string Enum_HotKeyAction_NavigateBack {
            get {
                return ResourceManager.GetString("Enum_HotKeyAction_NavigateBack", resourceCulture);
            }
        }
        
        public static string Enum_HotKeyAction_NavigateForward {
            get {
                return ResourceManager.GetString("Enum_HotKeyAction_NavigateForward", resourceCulture);
            }
        }
        
        public static string Enum_HotKeyAction_NavigateUp {
            get {
                return ResourceManager.GetString("Enum_HotKeyAction_NavigateUp", resourceCulture);
            }
        }
        
        public static string Enum_HotKeyAction_Open {
            get {
                return ResourceManager.GetString("Enum_HotKeyAction_Open", resourceCulture);
            }
        }
        
        public static string Enum_HotKeyAction_ReopenClosed {
            get {
                return ResourceManager.GetString("Enum_HotKeyAction_ReopenClosed", resourceCulture);
            }
        }
        
        public static string Enum_HotKeyAction_SetTargetWindow {
            get {
                return ResourceManager.GetString("Enum_HotKeyAction_SetTargetWindow", resourceCulture);
            }
        }
        
        public static string Enum_HotKeyAction_SnapDown {
            get {
                return ResourceManager.GetString("Enum_HotKeyAction_SnapDown", resourceCulture);
            }
        }
        
        public static string Enum_HotKeyAction_SnapLeft {
            get {
                return ResourceManager.GetString("Enum_HotKeyAction_SnapLeft", resourceCulture);
            }
        }
        
        public static string Enum_HotKeyAction_SnapRight {
            get {
                return ResourceManager.GetString("Enum_HotKeyAction_SnapRight", resourceCulture);
            }
        }
        
        public static string Enum_HotKeyAction_SnapUp {
            get {
                return ResourceManager.GetString("Enum_HotKeyAction_SnapUp", resourceCulture);
            }
        }
        
        public static string Enum_HotKeyAction_TabSearch {
            get {
                return ResourceManager.GetString("Enum_HotKeyAction_TabSearch", resourceCulture);
            }
        }
        
        public static string Enum_HotKeyAction_ToggleReuseTabs {
            get {
                return ResourceManager.GetString("Enum_HotKeyAction_ToggleReuseTabs", resourceCulture);
            }
        }
        
        public static string Enum_HotKeyAction_ToggleVisibility {
            get {
                return ResourceManager.GetString("Enum_HotKeyAction_ToggleVisibility", resourceCulture);
            }
        }
        
        public static string Enum_HotKeyAction_ToggleWinHook {
            get {
                return ResourceManager.GetString("Enum_HotKeyAction_ToggleWinHook", resourceCulture);
            }
        }
        
        public static string Menu_Open {
            get {
                return ResourceManager.GetString("Menu_Open", resourceCulture);
            }
        }
        
        public static string Msg_HideTrayIcon_Fail {
            get {
                return ResourceManager.GetString("Msg_HideTrayIcon_Fail", resourceCulture);
            }
        }
        
        public static string Msg_HideTrayIcon_Success {
            get {
                return ResourceManager.GetString("Msg_HideTrayIcon_Success", resourceCulture);
            }
        }
        
        public static string Nav_About {
            get {
                return ResourceManager.GetString("Nav_About", resourceCulture);
            }
        }
        
        public static string Nav_About_Tooltip {
            get {
                return ResourceManager.GetString("Nav_About_Tooltip", resourceCulture);
            }
        }
        
        public static string Nav_Preferences {
            get {
                return ResourceManager.GetString("Nav_Preferences", resourceCulture);
            }
        }
        
        public static string Nav_Preferences_Tooltip {
            get {
                return ResourceManager.GetString("Nav_Preferences_Tooltip", resourceCulture);
            }
        }
        
        public static string Nav_Shortcuts {
            get {
                return ResourceManager.GetString("Nav_Shortcuts", resourceCulture);
            }
        }
        
        public static string Nav_Shortcuts_Tooltip {
            get {
                return ResourceManager.GetString("Nav_Shortcuts_Tooltip", resourceCulture);
            }
        }
        
        public static string Prefs_AppSettings {
            get {
                return ResourceManager.GetString("Prefs_AppSettings", resourceCulture);
            }
        }
        
        public static string Prefs_AutoUpdate {
            get {
                return ResourceManager.GetString("Prefs_AutoUpdate", resourceCulture);
            }
        }
        
        public static string Prefs_AutoUpdate_Tooltip {
            get {
                return ResourceManager.GetString("Prefs_AutoUpdate_Tooltip", resourceCulture);
            }
        }
        
        public static string Prefs_HideTrayIcon {
            get {
                return ResourceManager.GetString("Prefs_HideTrayIcon", resourceCulture);
            }
        }
        
        public static string Prefs_HideTrayIcon_Tooltip {
            get {
                return ResourceManager.GetString("Prefs_HideTrayIcon_Tooltip", resourceCulture);
            }
        }
        
        public static string Prefs_RestoreWindows {
            get {
                return ResourceManager.GetString("Prefs_RestoreWindows", resourceCulture);
            }
        }
        
        public static string Prefs_RestoreWindows_Tooltip {
            get {
                return ResourceManager.GetString("Prefs_RestoreWindows_Tooltip", resourceCulture);
            }
        }
        
        public static string Prefs_SaveHistory {
            get {
                return ResourceManager.GetString("Prefs_SaveHistory", resourceCulture);
            }
        }
        
        public static string Prefs_SaveHistory_Tooltip {
            get {
                return ResourceManager.GetString("Prefs_SaveHistory_Tooltip", resourceCulture);
            }
        }
        
        public static string Prefs_ThemeIssues {
            get {
                return ResourceManager.GetString("Prefs_ThemeIssues", resourceCulture);
            }
        }
        
        public static string Prefs_ThemeIssues_Tooltip {
            get {
                return ResourceManager.GetString("Prefs_ThemeIssues_Tooltip", resourceCulture);
            }
        }
        
        public static string Profile_Action {
            get {
                return ResourceManager.GetString("Profile_Action", resourceCulture);
            }
        }
        
        public static string Profile_Action_Tooltip {
            get {
                return ResourceManager.GetString("Profile_Action_Tooltip", resourceCulture);
            }
        }
        
        public static string Profile_Delay {
            get {
                return ResourceManager.GetString("Profile_Delay", resourceCulture);
            }
        }
        
        public static string Profile_Delay_Tooltip {
            get {
                return ResourceManager.GetString("Profile_Delay_Tooltip", resourceCulture);
            }
        }
        
        public static string Profile_Delete_Tooltip {
            get {
                return ResourceManager.GetString("Profile_Delete_Tooltip", resourceCulture);
            }
        }
        
        public static string Profile_Enable_Tooltip {
            get {
                return ResourceManager.GetString("Profile_Enable_Tooltip", resourceCulture);
            }
        }
        
        public static string Profile_Handled {
            get {
                return ResourceManager.GetString("Profile_Handled", resourceCulture);
            }
        }
        
        public static string Profile_Handled_Tooltip {
            get {
                return ResourceManager.GetString("Profile_Handled_Tooltip", resourceCulture);
            }
        }
        
        public static string Profile_Hotkeys {
            get {
                return ResourceManager.GetString("Profile_Hotkeys", resourceCulture);
            }
        }
        
        public static string Profile_Hotkeys_Tooltip {
            get {
                return ResourceManager.GetString("Profile_Hotkeys_Tooltip", resourceCulture);
            }
        }
        
        public static string Profile_Location {
            get {
                return ResourceManager.GetString("Profile_Location", resourceCulture);
            }
        }
        
        public static string Profile_Location_Tooltip {
            get {
                return ResourceManager.GetString("Profile_Location_Tooltip", resourceCulture);
            }
        }
        
        public static string Profile_MoreOptions_Tooltip {
            get {
                return ResourceManager.GetString("Profile_MoreOptions_Tooltip", resourceCulture);
            }
        }
        
        public static string Profile_Name {
            get {
                return ResourceManager.GetString("Profile_Name", resourceCulture);
            }
        }
        
        public static string Profile_Name_Tooltip {
            get {
                return ResourceManager.GetString("Profile_Name_Tooltip", resourceCulture);
            }
        }
        
        public static string Profile_OpenAsTab {
            get {
                return ResourceManager.GetString("Profile_OpenAsTab", resourceCulture);
            }
        }
        
        public static string Profile_OpenAsTab_Tooltip {
            get {
                return ResourceManager.GetString("Profile_OpenAsTab_Tooltip", resourceCulture);
            }
        }
        
        public static string Profile_Scope {
            get {
                return ResourceManager.GetString("Profile_Scope", resourceCulture);
            }
        }
        
        public static string Profile_Scope_Tooltip {
            get {
                return ResourceManager.GetString("Profile_Scope_Tooltip", resourceCulture);
            }
        }
        
        public static string Shortcuts_AutoSave {
            get {
                return ResourceManager.GetString("Shortcuts_AutoSave", resourceCulture);
            }
        }
        
        public static string Shortcuts_AutoSave_Tooltip {
            get {
                return ResourceManager.GetString("Shortcuts_AutoSave_Tooltip", resourceCulture);
            }
        }
        
        public static string Shortcuts_Export {
            get {
                return ResourceManager.GetString("Shortcuts_Export", resourceCulture);
            }
        }
        
        public static string Shortcuts_Export_Tooltip {
            get {
                return ResourceManager.GetString("Shortcuts_Export_Tooltip", resourceCulture);
            }
        }
        
        public static string Shortcuts_Import {
            get {
                return ResourceManager.GetString("Shortcuts_Import", resourceCulture);
            }
        }
        
        public static string Shortcuts_Import_Tooltip {
            get {
                return ResourceManager.GetString("Shortcuts_Import_Tooltip", resourceCulture);
            }
        }
        
        public static string Shortcuts_New {
            get {
                return ResourceManager.GetString("Shortcuts_New", resourceCulture);
            }
        }
        
        public static string Shortcuts_New_Tooltip {
            get {
                return ResourceManager.GetString("Shortcuts_New_Tooltip", resourceCulture);
            }
        }
        
        public static string Shortcuts_Save {
            get {
                return ResourceManager.GetString("Shortcuts_Save", resourceCulture);
            }
        }
        
        public static string Shortcuts_Save_Tooltip {
            get {
                return ResourceManager.GetString("Shortcuts_Save_Tooltip", resourceCulture);
            }
        }
        
        public static string Status_KeyboardHook {
            get {
                return ResourceManager.GetString("Status_KeyboardHook", resourceCulture);
            }
        }
        
        public static string Status_MouseHook {
            get {
                return ResourceManager.GetString("Status_MouseHook", resourceCulture);
            }
        }
        
        public static string Status_ReuseTabs {
            get {
                return ResourceManager.GetString("Status_ReuseTabs", resourceCulture);
            }
        }
        
        public static string Status_WindowHook {
            get {
                return ResourceManager.GetString("Status_WindowHook", resourceCulture);
            }
        }
        
        public static string Tray_AddToStartup {
            get {
                return ResourceManager.GetString("Tray_AddToStartup", resourceCulture);
            }
        }
        
        public static string Tray_AddToStartup_Tooltip {
            get {
                return ResourceManager.GetString("Tray_AddToStartup_Tooltip", resourceCulture);
            }
        }
        
        public static string Tray_CheckForUpdates {
            get {
                return ResourceManager.GetString("Tray_CheckForUpdates", resourceCulture);
            }
        }
        
        public static string Tray_CheckForUpdates_Tooltip {
            get {
                return ResourceManager.GetString("Tray_CheckForUpdates_Tooltip", resourceCulture);
            }
        }
        
        public static string Tray_Exit {
            get {
                return ResourceManager.GetString("Tray_Exit", resourceCulture);
            }
        }
        
        public static string Tray_Exit_Tooltip {
            get {
                return ResourceManager.GetString("Tray_Exit_Tooltip", resourceCulture);
            }
        }
        
        public static string Tray_KeyboardHook_Tooltip {
            get {
                return ResourceManager.GetString("Tray_KeyboardHook_Tooltip", resourceCulture);
            }
        }
        
        public static string Tray_MouseHook_Tooltip {
            get {
                return ResourceManager.GetString("Tray_MouseHook_Tooltip", resourceCulture);
            }
        }
        
        public static string Tray_ReuseTabs_Tooltip {
            get {
                return ResourceManager.GetString("Tray_ReuseTabs_Tooltip", resourceCulture);
            }
        }
        
        public static string Tray_Settings {
            get {
                return ResourceManager.GetString("Tray_Settings", resourceCulture);
            }
        }
        
        public static string Tray_Settings_Tooltip {
            get {
                return ResourceManager.GetString("Tray_Settings_Tooltip", resourceCulture);
            }
        }
        
        public static string Tray_WindowHook_Tooltip {
            get {
                return ResourceManager.GetString("Tray_WindowHook_Tooltip", resourceCulture);
            }
        }
    }
} 