//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExplorerTabUtility.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExplorerTabUtility.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be the first to support this project!.
        /// </summary>
        public static string About_BeFirstSupporter {
            get {
                return ResourceManager.GetString("About_BeFirstSupporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Me A Coffee.
        /// </summary>
        public static string About_BuyMeACoffee {
            get {
                return ResourceManager.GetString("About_BuyMeACoffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Supporters.
        /// </summary>
        public static string About_CurrentSupporters {
            get {
                return ResourceManager.GetString("About_CurrentSupporters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhance your Windows File Explorer experience.
        /// </summary>
        public static string About_Description {
            get {
                return ResourceManager.GetString("About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        public static string About_Developer {
            get {
                return ResourceManager.GetString("About_Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Sponsors.
        /// </summary>
        public static string About_GitHubSponsors {
            get {
                return ResourceManager.GetString("About_GitHubSponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patreon.
        /// </summary>
        public static string About_Patreon {
            get {
                return ResourceManager.GetString("About_Patreon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal.
        /// </summary>
        public static string About_PayPal {
            get {
                return ResourceManager.GetString("About_PayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star on GitHub.
        /// </summary>
        public static string About_StarOnGitHub {
            get {
                return ResourceManager.GetString("About_StarOnGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you find this utility helpful, consider supporting its development through one of these options:.
        /// </summary>
        public static string About_SupportDescription {
            get {
                return ResourceManager.GetString("About_SupportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your support helps keep this project alive.
        /// </summary>
        public static string About_SupportHelps {
            get {
                return ResourceManager.GetString("About_SupportHelps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support the Project.
        /// </summary>
        public static string About_SupportProject {
            get {
                return ResourceManager.GetString("About_SupportProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you to all the amazing people who support this project!.
        /// </summary>
        public static string About_SupportersDescription {
            get {
                return ResourceManager.GetString("About_SupportersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer Tab Utility.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open application menu.
        /// </summary>
        public static string Menu_Open {
            get {
                return ResourceManager.GetString("Menu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot hide tray icon if no hotkey is configured to toggle visibility..
        /// </summary>
        public static string Msg_HideTrayIcon_Fail {
            get {
                return ResourceManager.GetString("Msg_HideTrayIcon_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can show the app again by pressing {0}.
        /// </summary>
        public static string Msg_HideTrayIcon_Success {
            get {
                return ResourceManager.GetString("Msg_HideTrayIcon_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Nav_About {
            get {
                return ResourceManager.GetString("Nav_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the application and support options.
        /// </summary>
        public static string Nav_About_Tooltip {
            get {
                return ResourceManager.GetString("Nav_About_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string Nav_Preferences {
            get {
                return ResourceManager.GetString("Nav_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure application settings.
        /// </summary>
        public static string Nav_Preferences_Tooltip {
            get {
                return ResourceManager.GetString("Nav_Preferences_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts.
        /// </summary>
        public static string Nav_Shortcuts {
            get {
                return ResourceManager.GetString("Nav_Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure keyboard and mouse shortcuts.
        /// </summary>
        public static string Nav_Shortcuts_Tooltip {
            get {
                return ResourceManager.GetString("Nav_Shortcuts_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        public static string Prefs_AppSettings {
            get {
                return ResourceManager.GetString("Prefs_AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto update.
        /// </summary>
        public static string Prefs_AutoUpdate {
            get {
                return ResourceManager.GetString("Prefs_AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically check for updates on startup.
        /// </summary>
        public static string Prefs_AutoUpdate_Tooltip {
            get {
                return ResourceManager.GetString("Prefs_AutoUpdate_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide tray icon.
        /// </summary>
        public static string Prefs_HideTrayIcon {
            get {
                return ResourceManager.GetString("Prefs_HideTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide the system tray icon.
        /// </summary>
        public static string Prefs_HideTrayIcon_Tooltip {
            get {
                return ResourceManager.GetString("Prefs_HideTrayIcon_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore previous windows.
        /// </summary>
        public static string Prefs_RestoreWindows {
            get {
                return ResourceManager.GetString("Prefs_RestoreWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore previously opened windows after restart or crash.
        /// </summary>
        public static string Prefs_RestoreWindows_Tooltip {
            get {
                return ResourceManager.GetString("Prefs_RestoreWindows_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save closed history.
        /// </summary>
        public static string Prefs_SaveHistory {
            get {
                return ResourceManager.GetString("Prefs_SaveHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save closed windows history so you can reopen them later (ReopenClosed, Tab search).
        /// </summary>
        public static string Prefs_SaveHistory_Tooltip {
            get {
                return ResourceManager.GetString("Prefs_SaveHistory_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have theme issues.
        /// </summary>
        public static string Prefs_ThemeIssues {
            get {
                return ResourceManager.GetString("Prefs_ThemeIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use alternative window hiding method that preserves your custom File-Explorer theme. Enable this if you have theme-related issues.
        /// </summary>
        public static string Prefs_ThemeIssues_Tooltip {
            get {
                return ResourceManager.GetString("Prefs_ThemeIssues_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Profile_Action {
            get {
                return ResourceManager.GetString("Profile_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action to perform when the hotkeys are pressed.
        /// </summary>
        public static string Profile_Action_Tooltip {
            get {
                return ResourceManager.GetString("Profile_Action_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        public static string Profile_Delay {
            get {
                return ResourceManager.GetString("Profile_Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay in milliseconds before performing the action.
        /// </summary>
        public static string Profile_Delay_Tooltip {
            get {
                return ResourceManager.GetString("Profile_Delay_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this profile.
        /// </summary>
        public static string Profile_Delete_Tooltip {
            get {
                return ResourceManager.GetString("Profile_Delete_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable or disable this profile.
        /// </summary>
        public static string Profile_Enable_Tooltip {
            get {
                return ResourceManager.GetString("Profile_Enable_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handled.
        /// </summary>
        public static string Profile_Handled {
            get {
                return ResourceManager.GetString("Profile_Handled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent further processing of the hotkeys in other applications.
        /// </summary>
        public static string Profile_Handled_Tooltip {
            get {
                return ResourceManager.GetString("Profile_Handled_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys.
        /// </summary>
        public static string Profile_Hotkeys {
            get {
                return ResourceManager.GetString("Profile_Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard or mouse keys to listen for. Click to record a new key combination..
        /// </summary>
        public static string Profile_Hotkeys_Tooltip {
            get {
                return ResourceManager.GetString("Profile_Hotkeys_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Profile_Location {
            get {
                return ResourceManager.GetString("Profile_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to open when the hotkeys are pressed. (folder, file, website, CLSID).
        /// </summary>
        public static string Profile_Location_Tooltip {
            get {
                return ResourceManager.GetString("Profile_Location_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more options.
        /// </summary>
        public static string Profile_MoreOptions_Tooltip {
            get {
                return ResourceManager.GetString("Profile_MoreOptions_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Profile_Name {
            get {
                return ResourceManager.GetString("Profile_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the profile.
        /// </summary>
        public static string Profile_Name_Tooltip {
            get {
                return ResourceManager.GetString("Profile_Name_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        public static string Profile_OpenAsTab {
            get {
                return ResourceManager.GetString("Profile_OpenAsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open as tab instead of a new window.
        /// </summary>
        public static string Profile_OpenAsTab_Tooltip {
            get {
                return ResourceManager.GetString("Profile_OpenAsTab_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        public static string Profile_Scope {
            get {
                return ResourceManager.GetString("Profile_Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope of the hotkeys: Global (anywhere) or only when File Explorer is focused.
        /// </summary>
        public static string Profile_Scope_Tooltip {
            get {
                return ResourceManager.GetString("Profile_Scope_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto save.
        /// </summary>
        public static string Shortcuts_AutoSave {
            get {
                return ResourceManager.GetString("Shortcuts_AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically save profiles when closing the window.
        /// </summary>
        public static string Shortcuts_AutoSave_Tooltip {
            get {
                return ResourceManager.GetString("Shortcuts_AutoSave_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPORT.
        /// </summary>
        public static string Shortcuts_Export {
            get {
                return ResourceManager.GetString("Shortcuts_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export profiles to a file.
        /// </summary>
        public static string Shortcuts_Export_Tooltip {
            get {
                return ResourceManager.GetString("Shortcuts_Export_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPORT.
        /// </summary>
        public static string Shortcuts_Import {
            get {
                return ResourceManager.GetString("Shortcuts_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import profiles from a file.
        /// </summary>
        public static string Shortcuts_Import_Tooltip {
            get {
                return ResourceManager.GetString("Shortcuts_Import_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW.
        /// </summary>
        public static string Shortcuts_New {
            get {
                return ResourceManager.GetString("Shortcuts_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new profile.
        /// </summary>
        public static string Shortcuts_New_Tooltip {
            get {
                return ResourceManager.GetString("Shortcuts_New_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string Shortcuts_Save {
            get {
                return ResourceManager.GetString("Shortcuts_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persist all profile changes.
        /// </summary>
        public static string Shortcuts_Save_Tooltip {
            get {
                return ResourceManager.GetString("Shortcuts_Save_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Hook.
        /// </summary>
        public static string Status_KeyboardHook {
            get {
                return ResourceManager.GetString("Status_KeyboardHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Hook.
        /// </summary>
        public static string Status_MouseHook {
            get {
                return ResourceManager.GetString("Status_MouseHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reuse Tabs.
        /// </summary>
        public static string Status_ReuseTabs {
            get {
                return ResourceManager.GetString("Status_ReuseTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Hook.
        /// </summary>
        public static string Status_WindowHook {
            get {
                return ResourceManager.GetString("Status_WindowHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to startup.
        /// </summary>
        public static string Tray_AddToStartup {
            get {
                return ResourceManager.GetString("Tray_AddToStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically start Explorer Tab Utility when Windows starts.
        /// </summary>
        public static string Tray_AddToStartup_Tooltip {
            get {
                return ResourceManager.GetString("Tray_AddToStartup_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string Tray_CheckForUpdates {
            get {
                return ResourceManager.GetString("Tray_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if a newer version of Explorer Tab Utility is available.
        /// </summary>
        public static string Tray_CheckForUpdates_Tooltip {
            get {
                return ResourceManager.GetString("Tray_CheckForUpdates_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Tray_Exit {
            get {
                return ResourceManager.GetString("Tray_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Explorer Tab Utility and stop all hooks.
        /// </summary>
        public static string Tray_Exit_Tooltip {
            get {
                return ResourceManager.GetString("Tray_Exit_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable or disable keyboard shortcuts.
        /// </summary>
        public static string Tray_KeyboardHook_Tooltip {
            get {
                return ResourceManager.GetString("Tray_KeyboardHook_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable or disable mouse shortcuts.
        /// </summary>
        public static string Tray_MouseHook_Tooltip {
            get {
                return ResourceManager.GetString("Tray_MouseHook_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, navigates to existing tabs instead of opening duplicate tabs.
        /// </summary>
        public static string Tray_ReuseTabs_Tooltip {
            get {
                return ResourceManager.GetString("Tray_ReuseTabs_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Tray_Settings {
            get {
                return ResourceManager.GetString("Tray_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the settings window to configure the application.
        /// </summary>
        public static string Tray_Settings_Tooltip {
            get {
                return ResourceManager.GetString("Tray_Settings_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle automatic redirection of new Explorer windows to tabs.
        /// </summary>
        public static string Tray_WindowHook_Tooltip {
            get {
                return ResourceManager.GetString("Tray_WindowHook_Tooltip", resourceCulture);
            }
        }
    }
} 